name: test_2

on:
  pull_request:
  merge_group:

jobs:
  test_2:
    runs-on: ubuntu-latest
    if: github.event_name == 'merge_group' || contains(github.event.pull_request.labels.*.name, 'run-test-2')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: python test_2.py
